name: Update LeetCode Progress

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch LeetCode Stats & Update README
        uses: joshcai/leetcode-readme-action@v1.3.0
        with:
          leetcode-username: "Md_Danish"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Md Danish"
          git config --global user.email "abdanish2@gmail.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update LeetCode progress table"
          git push
